export const designTokens = {
  colors: {
    primary: "#181d26",
    primaryActive: "#0d1218",
    ink: "#181d26",
    body: "#333840",
    muted: "#41454d",
    hairline: "#dddddd",
    borderStrong: "#9297a0",
    canvas: "#ffffff",
    surfaceSoft: "#f8fafc",
    surfaceStrong: "#e0e2e6",
    surfaceDark: "#181d26",
    surfaceDarkElevated: "#1d1f25",
    signatureCoral: "#aa2d00",
    signatureForest: "#0a2e0e",
    signatureCream: "#f5e9d4",
    signaturePeach: "#fcab79",
    signatureMint: "#a8d8c4",
    signatureYellow: "#f4d35e",
    signatureMustard: "#d9a441",
    onPrimary: "#ffffff",
    onDark: "#ffffff",
    link: "#1b61c9",
    linkActive: "#1a3866",
    info: "#254fad",
    infoBorder: "#458fff",
    success: "#006400",
    successBorder: "#39bf45",
    destructive: "#8c1d18",
    errorSurface: "#fff1f0",
  },
  fontFamily: '"Inter Variable", "Segoe UI", system-ui, sans-serif',
  typography: {
    metadata: "13px",
    body: "14px",
    control: "16px",
    titleSmall: "18px",
    titleMedium: "20px",
    titleLarge: "24px",
    regular: 400,
    medium: 500,
    semibold: 600,
  },
  spacing: {
    xxs: "4px",
    xs: "8px",
    sm: "12px",
    md: "16px",
    lg: "24px",
    xl: "32px",
    xxl: "48px",
    section: "96px",
  },
  radii: {
    control: "6px",
    card: "10px",
    panel: "12px",
  },
  border: {
    hairline: "1px",
    focus: "2px",
  },
  effects: {
    gradient: "none",
    shadow: "0 1px 2px rgb(24 29 38 / 8%)",
  },
  targets: {
    minimumDesktop: "32px",
    textControl: "44px",
  },
} as const;

export const primitiveStateClassNames = {
  default: "is-default",
  hover: "is-hover",
  active: "is-active",
  focus: "is-focus-visible",
  disabled: "is-disabled",
  destructive: "is-destructive",
  error: "is-error",
} as const;
